### PR TITLE
Make possible to add custom animations.

### PR DESCRIPTION
**Pull request by Samback**

### CODE REVIEW

**Comment by ninjaprox** [comment]
@Samback: Thanks for your contribution! This feature is planed on version 3.x. Could you recreate PR to `features/custom-animation` branch?

**Comment by Samback** [comment]
Yes, sure I will.

**Comment by Samback** [comment]
@ninjaprox Could you please tell me how you want to do that? Because now I see also your branch with such a name. And our implementation a little bit different.

**Comment by ninjaprox** [comment]
@Samback Please refer PR #39. We had discussion on this and it would be great to have your thought.

**Pull request closed without merging**
