### PR TITLE
UI blocker PR for new feature branch

### PR DESCRIPTION
**Pull request by basememara**
Thread started in #36.

### CODE REVIEW

**Comment by ninjaprox** [comment]
Thanks 👍

**Comment by loicgriffie** [comment]
If i'm not mistaken, the frame parameter is missing from the method signature

/**
     Create a activity indicator view with specified frame, type, color and padding and start animation.

```
 - parameter frame: view's frame.
 - parameter type: animation type, value of NVActivityIndicatorType enum. Default type is BallSpinFadeLoader.
 - parameter color: color of activity indicator view. Default color is white.
 - parameter padding: view's padding. Default padding is 0.
 */
public func startActivityAnimating(message: String? = default, type: NVActivityIndicatorView.NVActivityIndicatorType? = default, color: UIColor? = default, padding: CGFloat? = default)
```

**Comment by basememara** [comment]
Oh that was a typo in the documentation (copied and pasted too much). Instead of frame, it should be:

```
parameter message: message displayed under the animation.
```

**Comment by ninjaprox** [comment]
I fixed the documentation as well.

**Comment by loicgriffie** [comment]
Sad. I did expect to be able to define the frame :) Because the size of the loading view is way to big by default. It would be great to have a parameter to define the loading view size.

I have start some work on it to be able to specify the loader size. Hope to provide a pull request soon

**Comment by basememara** [comment]
Cool, that's a good idea!

It should probably be with the global defaults since it should remain consistent within the same app and shouldn't change much.

**Pull request merged**
