### PR TITLE
Added custom animations capability.

### PR DESCRIPTION
**Pull request by basememara**
Now you can create your own custom animations and feed it into `NVActivityIndicatorView`!

To use, conform your custom animation class to `NVActivityIndicatorAnimationDelegate` and use it:

```
startActivityAnimating("Loading...", type: CustomActivityIndicator())
```

### CODE REVIEW

**Comment by ninjaprox** [comment]
I think this is useful feature and would like to release this in version 3.x. However, I merged to `master` branch by mistake so I will reverted these commits on `master` and they are still there on `features/custom-animation`. Sorry for this inconvenience 👻.

**Comment by ninjaprox** [comment]
Btw, thanks to this, we have new audio equalizer animation in version 2.x 🎵.

**Comment by basememara** [comment]
Nice, glad I could help. Sounds good for v3. I think the code I put for this can be cleaned up a bit. I make an assumption in it that if the `customType` is `nil` then use the enum, which doesn't sit well with me.

Also, it would be great if you can post a roadmap in the readme if you had one in mind. Maybe we can add/adjust ideas and PR's 🤔

**Comment by basememara** [comment]
Oh and next time I create a PR, I'll ask you to open a branch 👍

**Comment by basememara** [comment]
Hey I have a better idea on implementing this. Instead of an overloaded function, maybe we create an extra enum case called `Custom` that would accept an animation instance, like this:

```
startActivityAnimating(type: .Orbit)
startActivityAnimating(type: .Custom(MyAnimation())
```

**Comment by ninjaprox** [comment]
Great, that's also what I'm thinking of. However `NVActivityIndicatorType` is enum with raw values for now so if using `.Custom(MyAnimation()`, we need to change the whole `NVActivityIndicatorType` to enum with associated values and it will affect other places.
Secondly, `NVActivityIndicatorView` is supporting to change its type on IB as well so we need to find out a way compatible with this or trade off this ability.
Additionally, it would be great to fully support Obj-C as well (currently some APIs are unavailable in Obj-C) in version 3.x.

**Comment by ninjaprox** [comment]
As for roadmap and ideas, PR discussions, sure, we can learn from other projects to manage by using issues, tags,... Will find an appropriate way and kick it off.

**Comment by basememara** [comment]
Oooo I don't support giving obj-c love. What makes this lib unique and modern is that its pure Swift, so tying it to legacy will add awkwardness. I vote for letting obj-c die +1. I say v3 should be Swift 3 themed.

**Comment by ninjaprox** [comment]
Can't agree more.

**Comment by Samback** [comment]
As I see this solution is really look like what I did at https://github.com/ninjaprox/NVActivityIndicatorView/pull/42

**Pull request merged**
