### PR TITLE
Disable codesigning and avoid building test for Xcode 8.0 and Carthage.

### PR DESCRIPTION
**Pull request by mitsuse**
Please see the followings for details:
- https://github.com/Carthage/Carthage/issues/1378
- https://github.com/Carthage/Carthage/issues/903

### CODE REVIEW

**Comment by ninjaprox** [comment]
@mitsuse: Thanks for report this issue and helping fix it! Would this affect only Xcode 8.0?

**Comment by mitsuse** [comment]
Yes, this affects only Xcode 8.0! But, this is for Swift 2.3 rather than 3.0. I also built with Xcode 7.3 on Travis CI and tested with Carthage on the local environment.

**Comment by mitsuse** [comment]
In addition, I tried building with Xcode 8.0 beta on Travis, but it failed because xctool seems to have no support for Xcode 8.0 yet.
I tested on the local environment instead, and it succeeded:-)

**Comment by ninjaprox** [comment]
Oh it seems that we need 2 separate versions to support both Swift 2.3 and 3.0 when Xcode 8 debuts officially. What do you think?

**Comment by mitsuse** [comment]
@ninjaprox Thanks!  I think support for both version is needed but new features (animations) are not needed in Swift 2.3, at least for me. We must use Swift 2.3 until other libraries migrate to Swift 3...

**Pull request merged**
