### PR TITLE
Added SwiftPM support

### PR DESCRIPTION
**Pull request by rafaelfrancisco-dev**

### CODE REVIEW

**Comment by gabors** [comment]
Dan this be merged please.

**Comment by makoni** [comment]
SwiftPM support would be nice

**Comment by lvnkmn** [comment]
I've tried adding this version as a package, however it failed because of missing UIKit imports... Looking forward to having a working version of this!

**Comment by gabors** [comment]
Interesting it worked just fine for me with both iOS and tvOS. 
I added from the fork listed in this pull request

**Comment by makoni** [comment]
Same for me. Just added dependency from the fork to existing project with Xcode and it worked just fine

**Comment by rafaelfrancisco-dev** [comment]
I only tested iOS integration, and it's been working fine on my current projects.

**Comment by ninjaprox** [comment]
Thanks for your patience. `4.8.0` is out with SPM support. 🚀

**Pull request merged**
