### PR TITLE
Update NVActivityIndicatorPresenter.swift

### LINKED ISSUE #180: stopAnimating() in state .waitingToShow issue
If you call stopAnimating() on a NVActivityIndicatorPresenter in the state .waitingToShow the state machine is broken. Later calls of startAnimating() will not work.

### PR DESCRIPTION
**Pull request by Spriter**
Fixing _hide() fixes #180

### CODE REVIEW

**Comment by Spriter** [comment]
Can you please merge this PR?

**Comment by ninjaprox** [comment]
@Spriter: Thanks for the PR 👍

**Comment by Spriter** [comment]
Can you release a new version on cocoapods? :)

**Comment by ninjaprox** [comment]
@Spriter: It's been shipped in `4.0.1` :rocket:

**Comment by Spriter** [comment]
thx 👍

**Pull request merged**
